### ISSUE TITLE
Wie kompliziert is basemap für die Teilnehmer zu installieren?

### ISSUE THREAD

**Issue by krother** [veit-schiele-communications/datenanalyse-in-python#2]
selbst auf neuem Ubuntu from scratch ausprobieren, dann weiter sehen.

**Comment by deeplook** [comment]
Basemap is not pop-installable, but conda-installable, see https://github.com/deeplook/backend-code-challenge/blob/master/requirements.txt

**Comment by krother** [comment]
Thanks!!
